version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.6.1
    steps:
      - restore_cache:
          keys:
            - R-package-library
      - checkout

      # install deps and check pkg ---------------------------------------------
      - run:
          name: Install
          command: |
            export OMP_NUM_THREADS=2
            # for caching later
            DAY=$(date -d "$D" '+%d')
            sudo apt update
            sudo apt install -y libglu1-mesa-dev libgmp-dev libgs-dev libgdal-dev libproj-dev libgeos-dev libudunits2-dev jags
            echo -e 'options(Ncpus = 6, repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
            R -q -e 'print(parallel::detectCores())'
            R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
            R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
            R -q -e 'remotes::install_github("ropenscilabs/tic", upgrade = "always"); print(tic::dsl_load()); tic::prepare_all_stages()'
            R -q -e 'tic::before_install()'
            R -q -e 'tic::install()'
      - run:
          name: Check
          command: |
            cd project && R -q -e 'tic::before_script()'
            R -q -e 'tic::script()'
      # save R pkg cache -------------------------------------------------------
      - save_cache: # Caches dependencies with a cache key
          key: R-package-library-{{ DAY }}
          paths:
            - /usr/local/lib/R/site-library
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: R -q -e 'tic::deploy()'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circle-ci
